{% set name = "google-apitools" %}
{% set version = "0.5.31" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4af0dd6dd4582810690251f0b57a97c1873dadfda54c5bc195844c8907624170

build:
  number: 0
  noarch: python
  entry_points:
    - gen_client = apitools.gen.gen_client:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - fasteners >=0.14
    - httplib2 >=0.8
    - oauth2client >=1.4.12
    - python
    - six >=1.12.0

test:
  imports:
    - apitools
  commands:
    - pip check
    - gen_client --help
  requires:
    - pip

about:
  home: https://pypi.org/project/google-apitools/
  summary: client libraries for humans
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
